#! /bin/sh

# Start picom (compton)

# border width

picom &

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color "#282828"
bspc config focused_border_color "#928374"

bspc config border_width        5
bspc config border_radius       15
bspc config window_gap          26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a fcitx-configtool state=floating center=true
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/myStaff/wallpaper/1.jpg
# Reload .Xresources
#xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
fcitx
nm-applet &
# Change from ugly 'X' cursor when hovering over background
#xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
#betterlockscreen -u ~/Wallpapers/gruvbox.png
#exec $HOME/.config/polybar/launch.sh
xmodmap ~/.Xmodmap

# scrachpad init
st -c scratchpadU &
bspc rule -a scratchpadU sticky=on state=floating hidden=on rectangle=1000x1000+0+0 center=on
st -c scratchpadI &
bspc rule -a scratchpadI sticky=on state=floating hidden=on rectangle=1000x1000+0+0 center=on
