#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config border_radius       15
bspc config window_gap          26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------
# Set wallpaper
feh --bg-fill ~/Pictures/1.jpg
# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
#polybar -r example
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
#xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
#betterlockscreen -u ~/Wallpapers/gruvbox.png
# Start picom (compton)
picom
#exec $HOME/.config/polybar/launch.sh
