#! /bin/sh

# Clean up everthing
bspc rule -r "*"


sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color "#282828"
bspc config focused_border_color "#928374"

bspc config border_width        5
bspc config border_radius       15
bspc config window_gap          26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
# need to be false with dylan's rounded corner patch
bspc config gapless_monocle      false

bspc config pointer_modifier alt
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a fcitx-configtool state=floating center=true
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# Saladict popup window
bspc rule -a Chromium:crx_cdonnmffkdaoajfknoeeecmchibpmkmg state=floating
bspc rule -a Google-chrome:crx_cdonnmffkdaoajfknoeeecmchibpmkmg state=floating
#bspc rule -a Chromium:chromium state=floating
bspc rule -a Fcitx-config-gtk3:fcitx-config-gtk3 state=floating

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------

# -----------------------------------------------
# ----------------- autostart -------------------
# -----------------------------------------------
# Start picom (compton)
killall "picom"
picom &
killall "nm-applet"
nm-applet &
feh --bg-fill ~/myStaff/wallpaper/robinwall.png &
killall polybar
~/.config/polybar/launch.sh &
killall "fcitx"
fcitx &
# Change from ugly 'X' cursor when hovering over background
#xsetroot -cursor_name left_ptr
# Make betterlockscreen generate and cache a background image for locking
#betterlockscreen -u ~/Wallpapers/gruvbox.png
#exec $HOME/.config/polybar/launch.sh
xrdb -load ~/.Xresources &
xmodmap ~/.Xmodmap &

# scrachpad init
#st -c scratchpadU &
bspc rule -a scratchpadU sticky=on state=floating rectangle=1000x1700+0+0 center=on
bspc rule -a scratchpadI sticky=on state=floating rectangle=1000x1000+0+0 center=on
#bspc rule -a scratchpadU sticky=on state=floating hidden=on rectangle=1000x1700+0+0 center=on
#st -c scratchpadI &
#bspc rule -a scratchpadI sticky=on state=floating hidden=on rectangle=1000x1000+0+0 center=on

